### ISSUE TITLE
Avoid quadratic traversal in composeTxOutTranslationPairs

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/ouroboros-consensus#145]
Use an accumulator instead of this quadratic traversal

**Comment by jorisdral** [comment]
I've looked into this but since we're using `sop-core` types here, using an accumulator quickly becomes quite complex because we would have to performing operations on `NP`s like reversing, appending and/or `snoc`cing. Peeling off constructors and then putting them back is a straightforward way to write functions manipulating `NP` types, and I think that's fine here
