### ISSUE TITLE
Consistent use of HK wrappers

### ISSUE THREAD

**Issue by jasagredo** [input-output-hk/ouroboros-consensus#213]
https://github.com/input-output-hk/ouroboros-network/pull/4417#discussion_r1144385889
https://github.com/input-output-hk/ouroboros-network/pull/4417#discussion_r1144392799

We should make a consistent use of those newly introduced type aliases/wrappers.

**Comment by jorisdral** [comment]
Also, `composeWithTicked1`

**Comment by jorisdral** [comment]
I've done a scan over the code and I actually think it is mostly fine as is. Reasons:

* `TickedLedgerState` is just a type synonym for `Ticked1 (LedgerState blk)`, there is no harm in mixing the two.
* `FlipTickedLedgerState` is something we really only need for the `HardForkBlock` in order to partially it, and we can't define it with other combinators that we currently have (we need type composition of a kind similar to `(k3 -> k2 -> Type) -> (k1 -> k3) -> k1 -> k2 -> Type`).
* `ComposeWithTicked1` is unused, so I've removed it in #241. My mistake, since I added it :stuck_out_tongue:.
